bench_runner/templates/_benchmark.src.yml
I confirmed that this has an effect, i.e. the test run during PGO data collection isn't ignoring the PYTHON_UOPS environment variable.
=> Turn on Tier 2 during PGO (if the Tier 2 box is checked)

bench_runner/scripts/run_benchmarks.py, bench_runner/scripts/should_run.py, bench_runner/templates/_benchmark.src.yml, bench_runner/templates/_pystats.src.yml
This is to support the upcoming changes in https://github.com/python/cpython/pull/118339
=> Use new configure flags for Tier2 and JIT

README.md
The version at `v0.2.2` doesn't have a `__main__.py`. Running `python -m bench_runner install` fails with
```
No module named bench_runner.__main__; 'bench_runner' is a package and cannot be directly executed
```
`v0.25.0` works
Fixes gh-223.
=> gh-223: Fix installation instructions

README.md, bench_runner/runners.py
There may be no runners when `bench_runner install` is executed for the first time.
Fixes gh-225.
=> gh-225: Raise a more helpful error in `get_runners` when there are no runners

bench_runner/scripts/compare.py, bench_runner/templates/_pystats.src.yml
In order to run _pystats job with other non-Azure self-hosted machine. 
Fixed https://github.com/faster-cpython/bench_runner/issues/249.
=> gh-249: Replace azure with cloud in _pystats.yml

bench_runner/hpt.py, bench_runner/plot.py, bench_runner/result.py, bench_runner/scripts/remove_benchmark.py, bench_runner/scripts/run_benchmarks.py, bench_runner/templates/bench_runner.toml, pyproject.toml
simdjson doesn't support large ints, and some of our pystats collections now have counts that exceed its limits.
=> Don't use simdjson

bench_runner/scripts/notify.py
If we skip `publish` job, which means we don't have a public repo, then the notification message should not add the `-public`.
=> Fix notification message if skip publish job

bench_runner/flags.py, bench_runner/templates/_benchmark.src.yml, tests/test_gh.py
This adds a checkbox to build CPython with "latest" clang, and then will flag the results so we know it's a special configuration.
This only works with macOS and Linux right now.  Windows is possible but I plan to do it as a follow-on since it's a bit more involved.
Cc: @Fidget-Spinner, @brandtbucher
=> Fix #326: Add a checkbox to build with clang

bench_runner/templates/_benchmark.src.yml
=> Fix #323: Always accept local changes to resolve merge conflicts

bench_runner/templates/_benchmark.src.yml
Closes https://github.com/faster-cpython/bench_runner/issues/342
GCC defaults to full LTO with `--with-lto=yes` passed. Clang defaults to ThinLTO with `--with-lto=yes` passed. You need `--with-lto=full` to enable full LTO.
=> Use full LTO for all builds

bench_runner/templates/_benchmark.src.yml
Thanks to Chris Eibl, we can enable PGO for the clang-cl builds. This should be a pretty large boost according to Chris.
https://github.com/python/cpython/pull/129907
=> Enable PGO for ClangCl on Windows

PROVISIONING.md, bench_runner/templates/_benchmark.src.yml
Make the benchmark workflow for Windows work for free-threaded Python, which doesn't build 'python.exe' but only 'python3.14t.exe'.
=> Fix benchmarking on Windows for free-threaded Python

bench_runner/result.py
=> Fix #377: Provide a stable ordering for results

bench_runner/templates/_benchmark.src.yml, bench_runner/templates/_pystats.src.yml
This makes it an error to pass invalid configure flags, avoiding situations where typos in flags create misleading results.
=> Add --enable-option-checking=fatal to all configure calls.

bench_runner/plot.py
In svg generation, make temporary files in the output directory, to avoid cross-filesystem renames if /tmp is a different filesystem.
=> Avoid cross-filesystem renames in svg generation

bench_runner/scripts/run_benchmarks.py, bench_runner/templates/_benchmark.src.yml
Add support for explicit CPU affinity via a runner-configurable environment variable (either in the runner configuration, or in the environment of the GHA runner itself). This is useful when running on a host that can't use isolated CPUs (which pyperf automatically detects).
Also undo the changes made by `pyperf system tune` after the benchmark run. (The system is generally more performant without benchmark tuning, so this matters for other users of the host and for the compile time on a dedicated runner.)
=> Add support for explicit per-runner CPU affinity

bench_runner/scripts/run_benchmarks.py
Add support for passing --same-loops to pyperformance for regular runs (not just pystats) by setting the PYPERFORMANCE_LOOPS_FILE environment variable.
Specifying a reasonable number of loops for each runner makes my A-A tests go from ~2% variability down to ~0.5%.
=> Make loops.json files per-runner-configurable

bench_runner/__main__.py, bench_runner/scripts/synthesize_loops_file.py, tests/test_synthesize_loops_file.py
Add a command to synthesize a pyperformance loops file from one or more benchmark results.
=> Add synthesize_loops_file script

CHANGELOG.md, bench_runner/flags.py, bench_runner/plot.py, bench_runner/scripts/install.py, bench_runner/scripts/workflow.py, bench_runner/templates/_weekly.src.yml, tests/test_gh.py
=> Separate clang from tail calling

bench_runner/templates/benchmark.src.yml
This adds the selected runner in the workflow run name (or 'all' or '__really_all', if that's what they were scheduled on), which makes the workflow overview a lot more tenable if you have multiple runners.
The runner name currently gets added after the ref and before any flags for the run. I'm not sure which is more readable, but I think this probably makes most sense: the flags are not a property of the fork/ref, and though they're not a property of the runner either, it's more similar to that.
=> Add machine to run name

bench_runner/templates/_benchmark.src.yml
On my Windows runner, which has Python installs downloaded from python.org, `python` tries to open the Windows app store, which fails in amusing ways from the GHA runner. `py` seems to work just fine, though.
=> Use `py` instead of `python` on Windows

bench_runner/plot.py
In the generation of longitudinal plots, when finding the base comparison to compare against, use results without flags rather than whatever happens to be found first.
=> Fix longitudinal plots using the wrong base

README.md, bench_runner/plot.py, bench_runner/scripts/generate_results.py, bench_runner/templates/README.md, tests/data/bench_runner.toml
This produces by-benchmark longitudinal plots, for example:
<details>
<summary>Plot by benchmark</summary>
</details>
=> Add a by-benchmark longitudinal plot

README.md, bench_runner/plot.py, tests/data/bench_runner.toml
Add a 'runners' list to longitudinal and flag-effect plot configuration, to have them only plot a subset of runners. (Flag effects could already do this by mapping runners to themselves, but it's a bit unwieldy in practice.)
=> Add a 'runners' list to longitudinal and flag-effect plot configuration

bench_runner/result.py
We just hit so much data in our repo that I can no longer load all of it into memory on my local machine.
This will only keep up to a 100 result sets entirely in memory, and cache a few important values from each file.
=> Use LRU cache for loading benchmarking data

bench_runner/templates/workflow_bootstrap.src.py, bench_runner/util.py
I believe this is necessary for the "log groups" to show up right in GitHub's logs. (At least, the output was all messed up in my logs until I applied these changes.)
=> Fix logging groups for GitHub output so they collapse correctly.
